remote_theme: jekyll/minima

title: aldw
author:
  name: Alden Wu (goodtrailer)
  email: aldenwu0@gmail.com

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

header_pages:
  - README.md

paginate: 10
paginate_path: "/blog/page:num/"
show_excerpts: true

minima:
  social_links:
    - { platform: github, user_url: "https://github.com/goodtrailer" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/aldenwu0" }
    - { platform: youtube,        user_url: "https://www.youtube.com/@goodtrailer0" }
